safe: false
source: .
destination: ./_site
plugins_dir: ./_plugins
highlighter: rouge
markdown: kramdown
exclude: ['.git', '.travis.yml', '.travis.d', '.sass-cache', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'LICENSE.md', '.asset-cache', 'Dockerfile', '_scripts', 'vendor/']
encoding: utf-8

url: http://conferences.sigcomm.org
baseurl: /acm-icn/2023

# Configuration for site
title: ACM ICN 2023
logo:
  image: icn23-logo.png
  info: ACM ICN 2023

# ACM ICN'2023 tracking
google_analytics_id: G-F8VR0256LN

# program:
#   # If the specified file doesn't exist, there will be command-line dialog to create it
#   # (Currently hardcoded for a dummy robot.mcrobot.jr@gmail.com account permissions)
#   google_client_id: .travis.d/google_client_id.json
#   # Google spreadsheet with the conference data
#   spreadsheet: 1G9OH401jxwql8xLTBh0ArB73gWIWHFC0H1JfiAh4OFU

# program-at-glance:
#   google_client_id: .travis.d/google_client_id.json
#   spreadsheet:
#     - 1n_Tv8ZSahQp63Q0BCryc3BrVuzgn1ByiFdi2xZozbMw

sass:
  sass_dir: assets/css

  style: compressed
  sourcemap: always
